name: Migration Tool CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'tools/capsule-migrate/**'
      - '.github/workflows/migration-tool-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'tools/capsule-migrate/**'

jobs:
  test:
    name: Test Migration Tool
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: tools/capsule-migrate/package-lock.json

      - name: Install dependencies
        working-directory: tools/capsule-migrate
        run: npm ci

      - name: Lint code
        working-directory: tools/capsule-migrate
        run: npm run lint

      - name: Build TypeScript
        working-directory: tools/capsule-migrate
        run: npm run build

      - name: Run tests
        working-directory: tools/capsule-migrate
        run: npm test

      - name: Generate coverage report
        working-directory: tools/capsule-migrate
        run: npm run test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: tools/capsule-migrate/coverage/coverage-final.json
          flags: migration-tool
          name: migration-tool-${{ matrix.os }}-${{ matrix.node-version }}

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: tools/capsule-migrate/package-lock.json

      - name: Install dependencies
        working-directory: tools/capsule-migrate
        run: npm ci

      - name: Build tool
        working-directory: tools/capsule-migrate
        run: npm run build

      - name: Test analyze command
        working-directory: tools/capsule-migrate
        run: |
          node dist/cli/index.js analyze ../../packages/capsules/src/database

      - name: Test migrate command (dry-run)
        working-directory: tools/capsule-migrate
        run: |
          node dist/cli/index.js migrate \
            ../../packages/capsules/src/database \
            /tmp/test-migration \
            --dry-run

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: [test, integration-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: tools/capsule-migrate
        run: npm ci

      - name: Build
        working-directory: tools/capsule-migrate
        run: npm run build

      - name: Publish to NPM (if version changed)
        working-directory: tools/capsule-migrate
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true
